import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { pgTable, text, timestamp, jsonb, boolean } from "drizzle-orm/pg-core";
import { z } from "zod";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set. Did you forget to provision a database?");
}

export const episodeSchema = z.object({
  episodeId: z.string(),
  episodeNumber: z.number().int(),
  episodeTitle: z.string(),
  videoUrl: z.string(),
});

export type Episode = z.infer<typeof episodeSchema>;

export const mediaTable = pgTable("media", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  thumbnail: text("thumbnail").notNull().default(""),
  type: text("type").notNull().$type<"movie" | "series">(),
  movieUrl: text("movie_url"),
  episodes: jsonb("episodes").notNull().$type<Episode[]>().default([]),
  autoGenerated: boolean("auto_generated").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle(pool, { schema: { mediaTable } });
