import { Router, type IRouter, type Request, type Response } from "express";
import { db, mediaTable, type Episode } from "../db";
import { eq } from "drizzle-orm";
import { randomUUID } from "crypto";
import { requireAuth } from "./auth";
import { resolveVideoUrl } from "../lib/resolveVideoUrl";

const router: IRouter = Router();

function toApiItem(row: typeof mediaTable.$inferSelect) {
  return {
    id: row.id,
    title: row.title,
    description: row.description,
    thumbnail: row.thumbnail,
    type: row.type,
    movieUrl: row.movieUrl ?? null,
    episodes: (row.episodes as Episode[]) ?? [],
    autoGenerated: row.autoGenerated ?? false,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

router.get("/media", async (req: Request, res: Response) => {
  try {
    const { type, search } = req.query as { type?: string; search?: string };
    let rows = await db.select().from(mediaTable).orderBy(mediaTable.createdAt);

    if (type === "movie" || type === "series") {
      rows = rows.filter((r) => r.type === type);
    }
    if (search) {
      const q = search.toLowerCase();
      rows = rows.filter((r) => r.title.toLowerCase().includes(q));
    }

    res.json(rows.map(toApiItem));
  } catch (err) {
    req.log.error({ err }, "listMedia error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/media/resolve", (req: Request, res: Response) => {
  const { url } = req.query as { url?: string };
  if (!url) {
    res.status(400).json({ error: "Missing required query parameter: url" });
    return;
  }
  res.json(resolveVideoUrl(url));
});

router.get("/media/stats", async (req: Request, res: Response) => {
  try {
    const rows = await db.select().from(mediaTable);
    const movies = rows.filter((r) => r.type === "movie").length;
    const series = rows.filter((r) => r.type === "series").length;
    const totalEpisodes = rows.reduce(
      (acc, r) => acc + ((r.episodes as Episode[]) ?? []).length,
      0,
    );
    res.json({ total: rows.length, movies, series, totalEpisodes });
  } catch (err) {
    req.log.error({ err }, "getMediaStats error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/media/:id", async (req: Request, res: Response) => {
  try {
    const [row] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!row) {
      res.status(404).json({ error: "Not found" });
      return;
    }
    res.json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "getMedia error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/media", requireAuth, async (req: Request, res: Response) => {
  try {
    const { title, description, thumbnail, type, movieUrl, autoGenerated } = req.body as {
      title: string;
      description: string;
      thumbnail: string;
      type: "movie" | "series";
      movieUrl?: string | null;
      autoGenerated?: boolean;
    };

    if (!title || !type) {
      res.status(400).json({ error: "title and type are required" });
      return;
    }

    const id = randomUUID();
    const now = new Date();
    const [row] = await db
      .insert(mediaTable)
      .values({
        id,
        title,
        description: description ?? "",
        thumbnail: thumbnail ?? "",
        type,
        movieUrl: type === "movie" ? (movieUrl ?? null) : null,
        episodes: [],
        autoGenerated: autoGenerated ?? false,
        createdAt: now,
        updatedAt: now,
      })
      .returning();

    res.status(201).json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "createMedia error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.put("/media/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const [existing] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!existing) {
      res.status(404).json({ error: "Not found" });
      return;
    }

    const { title, description, thumbnail, type, movieUrl } = req.body as {
      title?: string;
      description?: string;
      thumbnail?: string;
      type?: "movie" | "series";
      movieUrl?: string | null;
    };

    const newType = type ?? existing.type;
    const [row] = await db
      .update(mediaTable)
      .set({
        title: title ?? existing.title,
        description: description ?? existing.description,
        thumbnail: thumbnail ?? existing.thumbnail,
        type: newType,
        movieUrl: newType === "movie" ? (movieUrl !== undefined ? movieUrl : existing.movieUrl) : null,
        episodes: newType === "series" ? (existing.episodes ?? []) : [],
        updatedAt: new Date(),
      })
      .where(eq(mediaTable.id, String(req.params.id)))
      .returning();

    res.json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "updateMedia error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.delete("/media/:id", requireAuth, async (req: Request, res: Response) => {
  try {
    const [existing] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!existing) {
      res.status(404).json({ error: "Not found" });
      return;
    }
    await db.delete(mediaTable).where(eq(mediaTable.id, String(req.params.id)));
    res.status(204).send();
  } catch (err) {
    req.log.error({ err }, "deleteMedia error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/media/:id/episodes", requireAuth, async (req: Request, res: Response) => {
  try {
    const [existing] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!existing) {
      res.status(404).json({ error: "Not found" });
      return;
    }
    if (existing.type !== "series") {
      res.status(400).json({ error: "Episodes can only be added to series" });
      return;
    }

    const { episodeNumber, episodeTitle, videoUrl } = req.body as {
      episodeNumber: number;
      episodeTitle: string;
      videoUrl: string;
    };

    const currentEpisodes: Episode[] = (existing.episodes as Episode[]) ?? [];
    const newEpisode: Episode = {
      episodeId: randomUUID(),
      episodeNumber,
      episodeTitle,
      videoUrl,
    };

    const [row] = await db
      .update(mediaTable)
      .set({
        episodes: [...currentEpisodes, newEpisode],
        updatedAt: new Date(),
      })
      .where(eq(mediaTable.id, String(req.params.id)))
      .returning();

    res.status(201).json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "addEpisode error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.put("/media/:id/episodes/:episodeId", requireAuth, async (req: Request, res: Response) => {
  try {
    const [existing] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!existing) {
      res.status(404).json({ error: "Not found" });
      return;
    }

    const currentEpisodes: Episode[] = (existing.episodes as Episode[]) ?? [];
    const episodeIndex = currentEpisodes.findIndex(
      (e) => e.episodeId === req.params.episodeId,
    );
    if (episodeIndex === -1) {
      res.status(404).json({ error: "Episode not found" });
      return;
    }

    const { episodeNumber, episodeTitle, videoUrl } = req.body as {
      episodeNumber?: number;
      episodeTitle?: string;
      videoUrl?: string;
    };

    const updatedEpisodes = [...currentEpisodes];
    updatedEpisodes[episodeIndex] = {
      ...updatedEpisodes[episodeIndex],
      ...(episodeNumber !== undefined && { episodeNumber }),
      ...(episodeTitle !== undefined && { episodeTitle }),
      ...(videoUrl !== undefined && { videoUrl }),
    };

    const [row] = await db
      .update(mediaTable)
      .set({ episodes: updatedEpisodes, updatedAt: new Date() })
      .where(eq(mediaTable.id, String(req.params.id)))
      .returning();

    res.json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "updateEpisode error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.delete("/media/:id/episodes/:episodeId", requireAuth, async (req: Request, res: Response) => {
  try {
    const [existing] = await db
      .select()
      .from(mediaTable)
      .where(eq(mediaTable.id, String(req.params.id)));
    if (!existing) {
      res.status(404).json({ error: "Not found" });
      return;
    }

    const currentEpisodes: Episode[] = (existing.episodes as Episode[]) ?? [];
    const updatedEpisodes = currentEpisodes.filter(
      (e) => e.episodeId !== req.params.episodeId,
    );

    const [row] = await db
      .update(mediaTable)
      .set({ episodes: updatedEpisodes, updatedAt: new Date() })
      .where(eq(mediaTable.id, String(req.params.id)))
      .returning();

    res.json(toApiItem(row));
  } catch (err) {
    req.log.error({ err }, "deleteEpisode error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
